# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  host: localhost
  adapter: mysql2
  database: bench-1mil-dev
  pool: 5
  timeout: 5000
  username: root
  password:

production:
  host: localhost
  adapter: mysql2
  encoding: utf8
  reconnect: false
  # database: bench-goliath-mysql-dev
  database: bench-1mil-dev
  pool: 5
  username: root
  password:

test:
  host: localhost
  adapter: mysql2
  database: bench-1mil-test
  pool: 5
  timeout: 5000
